---
Name: cms-dark-theme
After:
  - '#coreconfig'
---

# add to member
SilverStripe\Security\Member:
  extensions:
    - Sunnysideup\CMSDarkTheme\Model\Extensions\DarkThemePreference

# add to site config
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Sunnysideup\CMSDarkTheme\Model\Extensions\DarkThemePreference

# add to left and main
SilverStripe\Admin\LeftAndMain:
  help_links:
    'Switch Display Mode': '/admin/displaymode/'
  extensions:
    - Sunnysideup\CMSDarkTheme\Admin\Extensions\LeftAndMainDarkTheme
