---
Name: cms-dark-theme
After:
  - '#coreconfig'
---

SilverStripe\Security\Member:
  extensions:
    - Sunnysideup\CMSDarkTheme\Extensions\DarkThemePreference

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Sunnysideup\CMSDarkTheme\Extensions\DarkThemePreference


SilverStripe\Admin\LeftAndMain:
  help_links:
    'Switch Display Mode': '/admin/darkmode/'
